### ISSUE TITLE
other ppls loot is not styled

### ISSUE THREAD

**Issue by Revnae** [GoldpawsStuff/ChatCleaner#1]
other ppls loot is not styled

**Comment by goldpaw** [comment]
Yeah, I don't do groups, ever, which is probably why I never caught that. 

I'll look into modifying the filter to also include other players and players from other realms receiving loot! :+1:

**Comment by Gloo-bal** [comment]
great :D loving the addon otherwise :)

**Comment by Gloo-bal** [comment]
The new update is working but the names arnt beside their loot

**Comment by goldpaw** [comment]
Blergh. I thought I fixed that before uploading. Guess it's still not managing to filter out the names from the chat messages, then. 

Well that's a problem. That needs fixing.

**Comment by Gloo-bal** [comment]
But it is filtering but just not showing the name

**Comment by goldpaw** [comment]
Yeah, I know. It failed to pick the player names up, so it makes it lookg like group loot is all our own loot. Which is totally misleading and not the intention, of course. 

Doing some testing here, and it's because of how I looked for player names. Doing it a different way now, and have uploaded it to github, but going to find some groups and do some real testing before pushing it out to curseforge.

**Comment by goldpaw** [comment]
Seems like I'm getting it to somewhat work. :)

file:///home/lars/Pictures/Screenshot%20from%202021-12-15%2022-08-03.png

**Comment by Gloo-bal** [comment]
do not know how hard this is to put in but it would be great if you could add classcolor to the name in the grp
